version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/sumup/typeid)
        - dot
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/sumup/typeid
linters:
  default: none
  enable:
    - asciicheck
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - gocritic
    - gomoddirectives
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    errorlint:
      errorf: true
      asserts: false
      comparison: true
    exhaustive:
      default-signifies-exhaustive: true
    gocritic:
      disabled-checks:
        - sloppyReassign
        - whyNoLint
      enabled-tags:
        - diagnostic
        - style
        - performance
      settings:
        hugeParam:
          sizeThreshold: 512
    gomoddirectives:
      replace-local: true
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    nakedret:
      max-func-lines: 10
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    revive:
      rules:
        - name: blank-imports
          disabled: true
    staticcheck:
      checks:
        - all
    testifylint:
      enable:
        - bool-compare
        - compares
        - empty
        - error-is-as
        - error-nil
        - expected-actual
        - float-compare
        - len
        - suite-dont-use-pkg
        - suite-extra-assert-call
        - suite-thelper
    unparam:
      check-exported: false
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - dupl
          - err113
          - errcheck
          - errorlint
          - funlen
          - goconst
          - gocyclo
          - gosec
          - lll
          - noctx
          - prealloc
          - unparam
        path: _test\.go
