name: Github Actions

on:
  pull_request:
    paths:
      - '.github/**'

defaults:
  run:
    working-directory: ./.github

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          sparse-checkout: |
            .github

      - uses: reviewdog/action-actionlint@13465d022aa41c282f730be17574b5ce692d0186 # v1.78.1
        with:
          filter_mode: nofilter
          fail_on_error: true
          reporter: github-pr-check
